[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"

[context.production]
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
